Remove dependency to ocamlbuild.

diff --git a/rml/configure b/rml/configure
--- a/rml/configure
+++ b/rml/configure
@@ -274,16 +274,16 @@ fi
 ocamlcp=$compiler
 
 # checking for ocamlbuild
-set dummy ocamlbuild; compiler_name=$2
-echo -n "checking for $compiler_name... "
-if sh ./searchpath $compiler_name; then
-    echo "$compiler_name"
-    compiler=$compiler_name
-else
-    echo "not found"
-    { echo "configure: error: Cannot find $compiler_name." 1>&2; exit 1; }
-fi
-ocamlbuild=$compiler
+# set dummy ocamlbuild; compiler_name=$2
+# echo -n "checking for $compiler_name... "
+# if sh ./searchpath $compiler_name; then
+#     echo "$compiler_name"
+#     compiler=$compiler_name
+# else
+#     echo "not found"
+#     { echo "configure: error: Cannot find $compiler_name." 1>&2; exit 1; }
+# fi
+# ocamlbuild=$compiler
 
 
 # Finish generated files
@@ -296,7 +296,7 @@ echo "OCAMLOPT=$ocamlopt" >> config
 echo "OCAMLDEP=$ocamldep" >> config
 echo "OCAMLLEX=$ocamllex" >> config
 echo "OCAMLYACC=$ocamlyacc" >> config
-echo "OCAMLBUILD=$ocamlbuild" >> config
+# echo "OCAMLBUILD=$ocamlbuild" >> config
 echo "OCAMLFLAGS=$debug" >> config
 echo "OCAMLOPTFLAGS=$debug" >> config
 echo "OCAMLDEPFLAGS=-slash" >> config
